site_name: D-FAST Bank Erosion
site_description: A tool to perform a bank erosion analysis based on a number of D-Flow FM simulations.
site_url: https://deltares.github.io/D-FAST_Bank_Erosion/
repo_url: https://github.com/Deltares/D-FAST_Bank_Erosion
repo_name: Deltares/D-FAST_Bank_Erosion
theme:
  name: material
  language: en
  palette:
    - scheme: deltares
      toggle:
        icon: material/lightbulb-outline
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/lightbulb
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top

use_directory_urls: false

plugins:
  - search
  - mkdocs-jupyter
  - autorefs
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          rendering:
            show_root_toc_entry: false
            show_source: true
            show_signature_annotations: true
            heading_level: 3
            show_category_heading: false
            group_by_category: false
          selection:
            inherited_members: false
          options:
            show_root_heading: true
            show_signature_annotations: true
  - table-reader
  - tags
  - mike:
      # These fields are all optional; the defaults are as below...
      alias_type: symlink
      redirect_template: null
      deploy_prefix: ''
      canonical_version: null
      version_selector: true
      css_dir: css
      javascript_dir: js

markdown_extensions:
  - admonition
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed
  - pymdownx.details
  - pymdownx.highlight
  - toc:
      permalink: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

nav:
  - Home: "index.md"
  - How-to:
      - Installation:
          - "Local clone + Poetry": "guides/poetry.md"
      - Contributing:
          - "guides/contributing.md"
      - Documentation:
          - "guides/documentation.md"
      - Tools:
            - "guides/pre-commit-hooks.md"
            - "guides/doctest.md"
  - API Reference:
      - io.md
      - batch.md
      - cmd.md
      - gui.md
      - kernel.md
      - plotting.md
  - Release Notes: "changelog.md"

extra:
  version:
    provider: mike
  version_selector: true
copyright: Copyright &copy; 2022 Deltares