[project]
name = "d-fast-bank-erosion"
version = "3.0.1"
description = "A tool to perform a bank erosion analysis based on a number of D-Flow FM simulations."
readme = "README.md"
requires-python = ">=3.11.0,<3.15"
authors = [
    { name = "Stichting Deltares", email = "delft3d.support@deltares.nl" },
]
dependencies = [
    "numpy>=1.26.4",
    "netcdf4>=1.7.3,<2.0.0",
    "pandas>=1.5.3",
    "matplotlib>=3.8.4,<4.0.0",
    "geopandas>=0.14.4",
    "shapely>=2.1.0,<3.0.0",
    # Allow only Pillow versions below 11.2.0 or 11.3.0 and above to avoid CWE-122 vulnerability
    "Pillow!=11.2.*",
    "dfastio @ git+https://github.com/Deltares/D-FAST_Commons.git@0.1.0",
    "certifi==2025.1.31",
]

[project.optional-dependencies]
gui = [
    "pyside6>=6.10.1,<7.0.0",
]

[project.scripts]
dfastbe = "dfastbe.__main__:main"

[dependency-groups]
dev = [
    "pytest>=9.0.3,<10.0.0",
    "pytest-cov>=7.0.0,<8.0.0",
    "pyfakefs>=5.1.0,<6.0.0",
    "teamcity-messages>=1.32,<2.0.0",
    "pre-commit>=4.2.0,<5.0.0",
    "commitizen>=4.8.3,<5.0.0",
]
docs = [
    "mkdocs>=1.2,<2.0.0",
    "mkdocs-material>=9.5,<10.0.0",
    "mkdocstrings[python]>=0.27.0,<0.28.0",
    "pymdown-extensions>=10.12,<11.0.0",
    "mkdocs-autorefs>=1.2,<2.0.0",
    "mkdocs-macros-plugin>=1.3.7,<2.0.0",
    "mkdocs-table-reader-plugin>=3.1.0,<4.0.0",
    "mkdocs-jupyter>=0.25.1,<0.26.0",
    "mkdocs-mermaid2-plugin>=1.2.1,<2.0.0",
    "mike>=2.1.3,<3.0.0",
    "jupyter-contrib-nbextensions>=0.7.0,<0.8.0",
    "notebook<7.0",
]
binary = [
    "cftime>=1.6.3",
    "pyproj>=3.4.1,<4.0.0",
    "nuitka>=2.0.0,<3.0.0",
    "imageio>=2.33.1,<3.0.0",
    "fiona>=1.10.1,<2.0.0",
    "pytz>=2020.1",
]

[tool.poetry]
packages = [{ include = "dfastbe", from = "src" }]


[tool.coverage.run]
omit = [
    "tests/test_binaries/*",
]

[tool.coverage.report]
show_missing = true
fail_under = 61


[tool.flake8]
ignore = ["E501", "E203", "F821", "E722", "B001", "D401", "B006", "D202", "W503"]
max-line-length = 88

[tool.black]
profile = "flake8"
line-length = 88
skip-string-normalization = true  # Avoid unnecessary quote changes

[tool.isort]
profile = "black"
line_length = 88
multi_line_output = 3

[tool.commitizen]
name = "cz_conventional_commits"
version_provider = "pep621"
tag_format = "$version"
changelog_file = "docs/mkdocs/change-log.md"
update_changelog_on_bump = true
changelog_incremental = true
version_scheme = "pep440"



[tool.pytest.ini_options]
addopts = [ "--cov",
            "--cov-report=term",
            "--cov-report=html",
            "--cov-report=xml:coverage-reports/coverage.xml",
]
testpaths="tests"

markers = [
    "e2e: marks tests as e2e (deselect with '-m \"not e2e\"')",
    "binaries: marks tests as binaries (deselect with '-m \"not binaries\"')",
    "unit: marks tests as unit (deselect with '-m \"not unit\"')",
    "integration: marks tests as integration (deselect with '-m \"not integration\"')",
]

[build-system]
requires = ["poetry-core>=2.0.0"]
build-backend = "poetry.core.masonry.api"
